# Generated by Django 6.1.1 on 2026-09-06 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='título')),
                ('description', models.TextField(blank=True, default='', verbose_name='descrição')),
                ('price_cents', models.PositiveIntegerField(default=0, verbose_name='preço (centavos)')),
                ('duration_min', models.PositiveIntegerField(default=30, verbose_name='duração (min)')),
                ('active', models.BooleanField(default=True, verbose_name='ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, default='', max_length=30, verbose_name='telefone')),
                ('scheduled_date', models.DateField(verbose_name='data agendada')),
                ('scheduled_time', models.TimeField(verbose_name='hora agendada')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='pendente', max_length=12, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='scheduling.option')),
            ],
            options={
                'ordering': ['scheduled_date', 'scheduled_time', 'created_at'],
            },
        ),
    ]
