# Generated by Django 6.1.1 on 2026-09-06 19:14

import scheduling.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='description',
            field=models.TextField(blank=True, default='', validators=[scheduling.validators.validate_no_control_chars], verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='option',
            name='title',
            field=models.CharField(max_length=120, validators=[scheduling.validators.validate_no_control_chars], verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='name',
            field=models.CharField(max_length=150, validators=[scheduling.validators.validate_no_control_chars], verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30, validators=[scheduling.validators.validate_phone], verbose_name='telefone'),
        ),
    ]
